openapi: 3.1.0
info:
  title: IT/Science News Hub API
  version: 0.1.0
  description: |
    REST API for the IT/Science News Hub MVP. Provides access to daily and weekly
    article feeds and unified search results. Based on PRD requirements (PRD-12, PRD-8, PRD-16).
servers:
  - url: http://localhost:4000/api
paths:
  /articles/daily:
    get:
      summary: List daily articles by date
      parameters:
        - in: query
          name: date
          required: true
          description: Target date (YYYY-MM-DD)
          schema:
            type: string
            format: date
        - in: query
          name: category
          required: false
          schema:
            type: string
          description: Filter by category label (e.g., AI, 보안)
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
        - in: query
          name: size
          schema:
            type: integer
            minimum: 1
            maximum: 20
            default: 10
      responses:
        '200':
          description: Daily article page
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedArticles'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'
  /articles/weekly:
    get:
      summary: List weekly articles by week key
      parameters:
        - in: query
          name: week
          required: true
          description: Week key formatted as YYYY-MM-N (N=1~5)
          schema:
            type: string
        - in: query
          name: category
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
        - in: query
          name: size
          schema:
            type: integer
            minimum: 1
            maximum: 20
            default: 10
      responses:
        '200':
          description: Weekly article page
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedWeeklyArticles'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'
  /articles/sidebar/daily:
    get:
      summary: Recent daily dates
      responses:
        '200':
          description: Latest 14 dates (descending)
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: string
                      format: date
  /articles/sidebar/weekly:
    get:
      summary: Recent weekly buckets
      responses:
        '200':
          description: Latest 8 week identifiers
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: string
  /search:
    get:
      summary: Unified search across daily/weekly sources
      parameters:
        - in: query
          name: q
          required: true
          schema:
            type: string
          description: Search keywords
        - in: query
          name: cat
          schema:
            type: string
          description: Optional category filter
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 50
      responses:
        '200':
          description: Search results grouped by Daily/Weekly
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'
components:
  schemas:
    Article:
      type: object
      properties:
        id:
          type: string
        source:
          type: string
        title:
          type: string
        summary:
          type: string
          nullable: true
        link:
          type: string
          format: uri
        category:
          type: string
          nullable: true
        thumbnail:
          type: string
          format: uri
          nullable: true
        published_at:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time
          nullable: true
    WeeklyArticle:
      allOf:
        - $ref: '#/components/schemas/Article'
        - type: object
          properties:
            period_label:
              type: string
              nullable: true
    PaginatedMeta:
      type: object
      properties:
        page:
          type: integer
        size:
          type: integer
        total:
          type: integer
        hasMore:
          type: boolean
        filters:
          type: object
    PaginatedArticles:
      type: object
      properties:
        data:
          type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/Article'
            page:
              type: integer
            size:
              type: integer
            total:
              type: integer
            hasMore:
              type: boolean
            filters:
              type: object
    PaginatedWeeklyArticles:
      type: object
      properties:
        data:
          type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/WeeklyArticle'
            page:
              type: integer
            size:
              type: integer
            total:
              type: integer
            hasMore:
              type: boolean
            filters:
              type: object
    SearchResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            query:
              type: string
            filters:
              type: object
              properties:
                category:
                  type: string
                  nullable: true
                limit:
                  type: integer
            results:
              type: object
              properties:
                daily:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      source:
                        type: string
                      title:
                        type: string
                      summary:
                        type: string
                        nullable: true
                      link:
                        type: string
                        format: uri
                      category:
                        type: string
                        nullable: true
                      date:
                        type: string
                        format: date
                      published_at:
                        type: string
                        format: date-time
                        nullable: true
                      rank:
                        type: number
                weekly:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      source:
                        type: string
                      title:
                        type: string
                      summary:
                        type: string
                        nullable: true
                      link:
                        type: string
                        format: uri
                      category:
                        type: string
                        nullable: true
                      week:
                        type: string
                      period_label:
                        type: string
                        nullable: true
                      rank:
                        type: number
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            status:
              type: integer
            message:
              type: string
  responses:
    BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
