name: Ingest Weekly Articles

on:
  schedule:
    - cron: '0 3 * * 1' # Monday 12:00 KST
    - cron: '0 3 * * 4' # Thursday 12:00 KST
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      TZ: Asia/Seoul
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Run weekly ingest
        run: python services/ingest/run_ingest.py weekly --pages 1 --limit 4
